[package]
name = "hydra-channel-update-script"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
base64 = "0.22.1"
chrono = { version = "0.4.42", default-features = false, features = ["std", "now", "serde"] }
reqwest = { version = "0.13.1", features = ["blocking", "gzip", "json", "query"] }
rsa = { version = "0.9.9", features = ["sha2"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_repr = "0.1.20"
sha2 = "0.10.9"
